In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.ndim)

In [13]:
arr2= np.array((1,2,3,4))
print(arr2)

[1 2 3 4]


In [8]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(type(arr1))
print(arr1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [9]:
listarr = np.array([1, 2, 3, 4, 5])
print(listarr)

[1 2 3 4 5]


In [5]:
tuplearr= np.array((1, 2, 3, 4, 5))
print(tuplearr)

[1 2 3 4 5]


In [10]:
fromiterarr = np.fromiter((a for a in range(10)), int)
print(fromiterarr)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a2)
print(a2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [18]:
emp = np.ones([4, 3], dtype=int)
print(emp)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
