In [2]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [11]:
arr2= np.array((1,2,3,4))
print(arr2)

[1 2 3 4]


In [8]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(type(arr1))
print(arr1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [8]:
listarr = np.array([1, 2, 3, 4, 5])
print(listarr)

[1 2 3 4 5]


In [9]:
tuplearr= np.array((1, 2, 3, 4, 5))
print(tuplearr)

[1 2 3 4 5]


In [10]:
fromiterarr = np.fromiter((a for a in range(10)), int)
print(fromiterarr)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a2)
print(a2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [18]:
emp = np.ones([4, 3], dtype=int)
print(emp)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
print(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


In [4]:
print(np.linspace(1, 10, 3))



[ 1.   5.5 10. ]


In [5]:
print(np.zeros(5, dtype=int))

[0 0 0 0 0]


In [7]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
arr2= np.array((1,2,3,4))
print(arr2)
print(arr2.size)

[1 2 3 4]
4


In [15]:
print(len(arr2))

4


In [17]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
arr2.shape

(4,)

In [18]:
a2.shape

(3, 4)

In [19]:
a2.dtype

dtype('int32')

In [20]:
a2.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [21]:
a2.shape

(3, 4)

In [22]:
a2.tolist

<function ndarray.tolist>

In [23]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a2.dtype

dtype('int32')

In [26]:
type(a2)

numpy.ndarray

In [28]:
np.save("abc", np.arange(5))

In [29]:
np.save("abc2",a2)

In [32]:
print(np.load("abc2.npy"))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
x = np.arange(0, 10, 1)
print(x)
# X array saved in geekfile.txt
c = np.savetxt("file.txt", x, delimiter =', ')

[0 1 2 3 4 5 6 7 8 9]


In [34]:
d = np.loadtxt("file.txt")
print(d)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
# sorting a two dimensional
# numpy array using numpy.sort()
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
print(a)

arr1 = np.sort(a, axis = 0)
print ("Along first axis : \n", arr1)

# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)
print ("\nAlong Last axis : \n", arr2)

a = np.array([[12, 15], [10, 1]])
arr3 = np.sort(a, axis = None)
print ("\nAlong none axis : \n", arr3)


[[12 15]
 [10  1]]
Along first axis : 
 [[10  1]
 [12 15]]

Along Last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [42]:
# Adding the values at the end
# of a numpy array
arr = np.arange(1, 13).reshape(2, 6)
print("Original Array")
print(arr, "\n")


Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 



In [50]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

In [52]:
# Performing addition using numpy function
print("Addition:", np.add(a, b))

# Performing subtraction using numpy function
print("Subtraction:", np.subtract(a, b))

# Performing multiplication using numpy function
print("Multiplication:", np.multiply(a, b))

# Performing division using numpy functions
print("Division:", np.divide(a, b))

# Performing mod on two matrices
print("Mod:", np.mod(a, b))

#Performing remainder on two matrices
print("Remainder:", np.remainder(a,b))

# Performing power of two matrices
print("Power:", np.power(a, b))

# Performing Exponentiation
print("Exponentiation:", np.exp(b))

Addition: [  7  77  23 130]
Subtraction: [ 3 67  3 70]
Multiplication: [  10  360  130 3000]
Division: [ 2.5        14.4         1.3         3.33333333]
Mod: [ 1  2  3 10]
Remainder: [ 1  2  3 10]
Power: [        25 1934917632  419538377          0]
Exponentiation: [7.38905610e+00 1.48413159e+02 2.20264658e+04 1.06864746e+13]


In [54]:
# 1D array
arr = [20, 2, 7, 1, 34]
# mean
print("mean of arr:", np.mean(arr))

# median
print("median of arr:", np.median(arr))

# sum
print("Sum of arr(uint8):", np.sum(arr, dtype = np.uint8))

print("Sum of arr(float32):", np.sum(arr, dtype = np.float32))

# min and max
print("maximum element:", np.max(arr))
print("minimum element:", np.min(arr))

# var
print("var of arr:", np.var(arr))
print("var of arr(float32):", np.var(arr, dtype = np.float32))

# standard deviation
print("std of arr:", np.std(arr))
print ("More precision with float32", np.std(arr, dtype = np.float32))

mean of arr: 12.8
median of arr: 7.0
Sum of arr(uint8): 64
Sum of arr(float32): 64.0
maximum element: 34
minimum element: 1
var of arr: 158.16
var of arr(float32): 158.16
std of arr: 12.576167937809991
More precision with float32 12.576168
